freebsd_instance:
    image: freebsd-11-2-release-amd64

task:
    install_script:
        - pkg install -y cmake libevent git go
        - git clone https://boringssl.googlesource.com/boringssl
        - cd boringssl
        - git checkout chromium-stable
        - cmake .
        - make
        - ln -s ssl/libssl.a
        - ln -s crypto/libcrypto.a
        - cd -
    script:
        - cmake -DBORINGSSL_INCLUDE=$PWD/boringssl/include -DBORINGSSL_LIB=$PWD/boringssl .
        - make
        - make test
