version: 2.{branch}.{build}

image:
- MacOS

cache:
- boringssl -> boringssl-target.txt # we define the commit in here

build: off

init:

install:

- sh: >-

    if [[ -f ./boringssl/include/openssl/ssl.h ]] ; then

        echo boringssl cached

    else

        git clone https://boringssl.googlesource.com/boringssl

        cd boringssl

        git reset --hard $(<../boringssl-target.txt)

        rm -rf .git

        cd ..

    fi

    cd boringssl

    cmake .

    make -j2 crypto ssl decrepit

    cd ..

    git submodule init

    n=0

    until git submodule update --checkout --force --recursive ; do

        [ "$n" -ge 10 ] && exit 1

        n=$((n+1))

    done

    cmake -DBORINGSSL_DIR=$PWD/boringssl .

    make -j2 lsquic build-tests

test_script:

- sh:  >-

    make help

    make test

    make -j2 perf_server perf_client

    ./bin/perf_server -L notice -s ::1:8443 -c localhost,tests/localhost.pem,tests/localhost.key &

    PERF_SERVER_PID=$!

    time ./bin/perf_client -L info -s ::1:8443 -p 104857600:104857600

    kill $PERF_SERVER_PID
