version: 1.{branch}.{build}

image: Visual Studio 2022

cache:
- c:\tools\vcpkg -> c:\tools\vcpkg\.git\refs\heads\master
- boringssl -> boringssl-target.txt # we define the commit in here

environment:
  VCPKG_DISABLE_METRICS: 1

init:

- cmd: ''

install:

- cmd: >-

    call appveyor-update-vcpkg.cmd

    vcpkg install zlib:x64-windows

    vcpkg install libevent:x64-windows

    vcpkg install pcre2:x64-windows

    vcpkg install getopt:x64-windows

    vcpkg integrate install

    if exist c:\tools\vcpkg\buildtrees rd /s /q c:\tools\vcpkg\buildtrees

    if exist c:\tools\vcpkg\downloads rd /s /q c:\tools\vcpkg\downloads

build_script:

- cmd: appveyor-windows-shared.cmd

test_script:

- cmd: appveyor-windows-test.cmd

