#ifndef LSQUIC_CONFIG_H
#define LSQUIC_CONFIG_H

/* #undef HAVE_IP_DONTFRAG */
/* #undef HAVE_IP_MTU_DISCOVER */
#define HAVE_REGEX 1

#define LSQUIC_DONTFRAG_SUPPORTED (HAVE_IP_DONTFRAG || HAVE_IP_MTU_DISCOVER)

#endif
